import { Achievement, AchievementId } from '../types/game';

export function createAchievements(): Record<AchievementId, Achievement> {
  return {
    first_click: {
      id: 'first_click',
      name: 'First Spark',
      description: 'Click the Forge for the first time',
      unlocked: false,
      progress: 0,
      target: 1,
      reward: { shards: 1 },
    },
    click_100: {
      id: 'click_100',
      name: 'Enthusiastic Forger',
      description: 'Click the Forge 100 times',
      unlocked: false,
      progress: 0,
      target: 100,
      reward: { shards: 5 },
    },
    first_building: {
      id: 'first_building',
      name: 'Automation Begins',
      description: 'Purchase your first building',
      unlocked: false,
      progress: 0,
      target: 1,
      reward: { shards: 2 },
    },
    flux_1k: {
      id: 'flux_1k',
      name: 'Flux Master',
      description: 'Accumulate 1,000 Flux',
      unlocked: false,
      progress: 0,
      target: 1000,
      reward: { shards: 3 },
    },
    flux_1m: {
      id: 'flux_1m',
      name: 'Flux Titan',
      description: 'Accumulate 1,000,000 Flux',
      unlocked: false,
      progress: 0,
      target: 1000000,
      reward: { shards: 10 },
    },
    first_collapse: {
      id: 'first_collapse',
      name: 'Universe Collapsed',
      description: 'Collapse your first universe',
      unlocked: false,
      progress: 0,
      target: 1,
      reward: { shards: 5 },
    },
    collapse_10: {
      id: 'collapse_10',
      name: 'Cosmic Recycler',
      description: 'Collapse 10 universes',
      unlocked: false,
      progress: 0,
      target: 10,
      reward: { shards: 15 },
    },
    echoes_100: {
      id: 'echoes_100',
      name: 'Echo Collector',
      description: 'Earn 100 total Echo Crystals',
      unlocked: false,
      progress: 0,
      target: 100,
      reward: { shards: 20 },
    },
    trait_discovery: {
      id: 'trait_discovery',
      name: 'Multiverse Explorer',
      description: 'Discover 5 different Universe Traits',
      unlocked: false,
      progress: 0,
      target: 5,
      reward: { shards: 10 },
    },
  };
}
