import { Achievement, AchievementId } from '../types/game';

export type AchievementCategory = 'production' | 'collapses' | 'traits' | 'stages' | 'buildings' | 'general';

export interface AchievementWithCategory extends Achievement {
  category: AchievementCategory;
}

export function createAchievements(): Record<AchievementId, AchievementWithCategory> {
  return {
    first_click: {
      id: 'first_click',
      name: 'First Spark',
      description: 'Click the Forge for the first time',
      category: 'general',
      unlocked: false,
      progress: 0,
      target: 1,
      reward: { shards: 1 },
    },
    click_100: {
      id: 'click_100',
      name: 'Enthusiastic Forger',
      description: 'Click the Forge 100 times',
      category: 'production',
      unlocked: false,
      progress: 0,
      target: 100,
      reward: { shards: 5 },
    },
    click_1000: {
      id: 'click_1000',
      name: 'Click Master',
      description: 'Click the Forge 1,000 times',
      category: 'production',
      unlocked: false,
      progress: 0,
      target: 1000,
      reward: { shards: 10 },
    },
    first_building: {
      id: 'first_building',
      name: 'Automation Begins',
      description: 'Purchase your first building',
      category: 'buildings',
      unlocked: false,
      progress: 0,
      target: 1,
      reward: { shards: 2 },
    },
    buildings_50: {
      id: 'buildings_50',
      name: 'Industrial Tycoon',
      description: 'Own 50 total buildings',
      category: 'buildings',
      unlocked: false,
      progress: 0,
      target: 50,
      reward: { shards: 8 },
    },
    buildings_200: {
      id: 'buildings_200',
      name: 'Cosmic Factory',
      description: 'Own 200 total buildings',
      category: 'buildings',
      unlocked: false,
      progress: 0,
      target: 200,
      reward: { shards: 15 },
    },
    flux_1k: {
      id: 'flux_1k',
      name: 'Flux Initiate',
      description: 'Accumulate 1,000 Flux',
      category: 'production',
      unlocked: false,
      progress: 0,
      target: 1000,
      reward: { shards: 3 },
    },
    flux_100k: {
      id: 'flux_100k',
      name: 'Flux Adept',
      description: 'Accumulate 100,000 Flux',
      category: 'production',
      unlocked: false,
      progress: 0,
      target: 100000,
      reward: { shards: 8 },
    },
    flux_1m: {
      id: 'flux_1m',
      name: 'Flux Master',
      description: 'Accumulate 1,000,000 Flux',
      category: 'production',
      unlocked: false,
      progress: 0,
      target: 1000000,
      reward: { shards: 15 },
    },
    flux_1b: {
      id: 'flux_1b',
      name: 'Flux Titan',
      description: 'Accumulate 1,000,000,000 Flux',
      category: 'production',
      unlocked: false,
      progress: 0,
      target: 1000000000,
      reward: { shards: 30 },
    },
    civilization_1k: {
      id: 'civilization_1k',
      name: 'Society Builder',
      description: 'Accumulate 1,000 Civilization',
      category: 'production',
      unlocked: false,
      progress: 0,
      target: 1000,
      reward: { shards: 5 },
    },
    civilization_100k: {
      id: 'civilization_100k',
      name: 'Galactic Empire',
      description: 'Accumulate 100,000 Civilization',
      category: 'production',
      unlocked: false,
      progress: 0,
      target: 100000,
      reward: { shards: 20 },
    },
    first_collapse: {
      id: 'first_collapse',
      name: 'Universe Collapsed',
      description: 'Collapse your first universe',
      category: 'collapses',
      unlocked: false,
      progress: 0,
      target: 1,
      reward: { shards: 5 },
    },
    collapse_10: {
      id: 'collapse_10',
      name: 'Cosmic Recycler',
      description: 'Collapse 10 universes',
      category: 'collapses',
      unlocked: false,
      progress: 0,
      target: 10,
      reward: { shards: 15 },
    },
    collapse_50: {
      id: 'collapse_50',
      name: 'Reality Engineer',
      description: 'Collapse 50 universes',
      category: 'collapses',
      unlocked: false,
      progress: 0,
      target: 50,
      reward: { shards: 30 },
    },
    echoes_10: {
      id: 'echoes_10',
      name: 'Echo Novice',
      description: 'Earn 10 total Echo Crystals',
      category: 'collapses',
      unlocked: false,
      progress: 0,
      target: 10,
      reward: { shards: 5 },
    },
    echoes_100: {
      id: 'echoes_100',
      name: 'Echo Collector',
      description: 'Earn 100 total Echo Crystals',
      category: 'collapses',
      unlocked: false,
      progress: 0,
      target: 100,
      reward: { shards: 20 },
    },
    echoes_1000: {
      id: 'echoes_1000',
      name: 'Echo Hoarder',
      description: 'Earn 1,000 total Echo Crystals',
      category: 'collapses',
      unlocked: false,
      progress: 0,
      target: 1000,
      reward: { shards: 50 },
    },
    trait_discovery: {
      id: 'trait_discovery',
      name: 'Multiverse Explorer',
      description: 'Discover 5 different Universe Traits',
      category: 'traits',
      unlocked: false,
      progress: 0,
      target: 5,
      reward: { shards: 10 },
    },
    trait_discovery_all: {
      id: 'trait_discovery_all',
      name: 'Omniversal Scholar',
      description: 'Discover all Universe Traits',
      category: 'traits',
      unlocked: false,
      progress: 0,
      target: 10,
      reward: { shards: 25 },
    },
    rare_trait: {
      id: 'rare_trait',
      name: 'Rare Reality',
      description: 'Complete a run with a Rare trait active',
      category: 'traits',
      unlocked: false,
      progress: 0,
      target: 1,
      reward: { shards: 8 },
    },
    mythic_trait: {
      id: 'mythic_trait',
      name: 'Mythic Master',
      description: 'Complete a run with a Mythic trait active',
      category: 'traits',
      unlocked: false,
      progress: 0,
      target: 1,
      reward: { shards: 15 },
    },
    stage_starbirth: {
      id: 'stage_starbirth',
      name: 'Stellar Ignition',
      description: 'Reach the Starbirth stage',
      category: 'stages',
      unlocked: false,
      progress: 0,
      target: 1,
      reward: { shards: 3 },
    },
    stage_planetfall: {
      id: 'stage_planetfall',
      name: 'World Builder',
      description: 'Reach the Planetfall stage',
      category: 'stages',
      unlocked: false,
      progress: 0,
      target: 1,
      reward: { shards: 5 },
    },
    stage_awakening: {
      id: 'stage_awakening',
      name: 'Life Giver',
      description: 'Reach the Awakening Life stage',
      category: 'stages',
      unlocked: false,
      progress: 0,
      target: 1,
      reward: { shards: 8 },
    },
    stage_civilizations: {
      id: 'stage_civilizations',
      name: 'Empire Forger',
      description: 'Reach the Civilizations stage',
      category: 'stages',
      unlocked: false,
      progress: 0,
      target: 1,
      reward: { shards: 12 },
    },
    stage_ascension: {
      id: 'stage_ascension',
      name: 'Transcendent',
      description: 'Reach the Ascension stage',
      category: 'stages',
      unlocked: false,
      progress: 0,
      target: 1,
      reward: { shards: 20 },
    },
    fast_run: {
      id: 'fast_run',
      name: 'Speedrunner',
      description: 'Collapse a universe in under 5 minutes',
      category: 'collapses',
      unlocked: false,
      progress: 0,
      target: 1,
      reward: { shards: 15 },
    },
  };
}
